In [21]:
import pandas as pd
import numpy as np

Processamento de dados:

In [22]:
# Tratando informações da tabela de todos os Leads 
df1 = pd.read_csv('olist_marketing_qualified_leads_dataset.csv', sep = ',')

In [23]:
# Tratando informações da tabela de acordos firmados 
df2 = pd.read_csv('olist_closed_deals_dataset.csv', sep = ',')

In [24]:
# Criando a coluna 'is_closed' na tabela de acodos fechados/firmados
df2['is_closed'] = True

- Criar tabela com todos os MQLs, com todas as informações disponíveis para cada um.

In [25]:
# Criando a tabela com todas as informações disponíveis
tabela_mqls = pd.merge(df1, df2, how='left', on='mql_id')

- Criar uma coluna com quais MQLs fecharam acordo e quais foram perdidos.

In [26]:
# Tratando NaN na coluna de 'is_closed' (True = Acordo Fechado / False = Acordo Perdido)
tabela_mqls['is_closed'] = tabela_mqls['is_closed'].fillna(False)
tabela_mqls.head(5)

,mql_id,first_contact_date,landing_page_id,origin,seller_id,sdr_id,sr_id,won_date,business_segment,lead_type,lead_behaviour_profile,has_company,has_gtin,average_stock,business_type,declared_product_catalog_size,declared_monthly_revenue,is_closed
0,dac32acd4db4c29c230538b72f8dd87d,2018-02-01,88740e65d5d6b056e0cda098e1ea6313,social,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1,8c18d1de7f67e60dbd64e3c07d7e9d5d,2017-10-20,007f9098284a86ee80ddeb25d53e0af8,paid_search,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
2,b4bc852d233dfefc5131f593b538befa,2018-03-22,a7982125ff7aa3b2054c6e44f9d28522,organic_search,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
3,6be030b81c75970747525b843c1ef4f8,2018-01-22,d45d558f0daeecf3cccdffe3c59684aa,email,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
4,5420aad7fec3549a85876ba1c529bd84,2018-02-21,b48ec5f3b04e9068441002a19df93c6c,organic_search,2c43fb513632d29b3b58df74816f1b06,a8387c01a09e99ce014107505b92388c,4ef15afb4b2723d8f3d81e51ec7afefe,2018-02-26 19:58:54,pet,online_medium,cat,NaN,NaN,NaN,reseller,NaN,0.0,True

Perguntas a serem respondidas:
- Qual foi a taxa de conversão total?

In [27]:
#Total de Leads
total_leads = tabela_mqls.is_closed.count()
total_leads

8000

In [28]:
#quantidade de linhas NÃO nulas - Acordos fechados
closed_deal = tabela_mqls.is_closed.sum()
closed_deal

842

In [29]:
tx_conv_total = closed_deal / total_leads
print("A taxa de conversão total foi de:", '{0:.3%}'.format(tx_conv_total))

A taxa de conversão total foi de: 10.525%

- Qual foi a taxa de conversão de cada origem?

In [30]:
conv_origem = tabela_mqls.groupby('origin')['is_closed'].count().to_frame('total')
conv_origem['closed'] = tabela_mqls.groupby('origin')['is_closed'].sum()
conv_origem['taxa'] = conv_origem['closed']/conv_origem['total']
conv_origem

                   total  closed      taxa
origin
direct_traffic       499      56  0.112224
display              118       6  0.050847
email                493      15  0.030426
organic_search      2296     271  0.118031
other                150       4  0.026667
other_publicities     65       3  0.046154
paid_search         1586     195  0.122951
referral             284      24  0.084507
social              1350      75  0.055556
unknown             1099     179  0.162875

In [37]:
#Outra forma de fazer o exemplo de cima =) thanks prof! 
def perc(x):
    return (x==1).astype(int).sum() / x.count()

tabela_mqls.groupby('origin').agg({'is_closed':
                                                ['sum', 
                                                'count', 
                                                perc]})

                  is_closed
                        sum count      perc
origin
direct_traffic           56   499  0.112224
display                   6   118  0.050847
email                    15   493  0.030426
organic_search          271  2296  0.118031
other                     4   150  0.026667
other_publicities         3    65  0.046154
paid_search             195  1586  0.122951
referral                 24   284  0.084507
social                   75  1350  0.055556
unknown                 179  1099  0.162875

- Qual foi a taxa de conversão de cada página inicial?

In [ ]:
conv_landing_page = tabela_mqls.groupby('landing_page_id')['is_closed'].count().to_frame('total')
conv_landing_page['closed'] = tabela_mqls.groupby('landing_page_id')['is_closed'].sum()
conv_landing_page['taxa'] = conv_landing_page['closed']/conv_landing_page['total']

conv_landing_page

                                  total  closed      taxa
landing_page_id
007f9098284a86ee80ddeb25d53e0af8     66       4  0.060606
01850876d34b43494b5f9879c366877b      1       0  0.000000
0218f6be0b76aca72ab4d00ee9e8cf10     48       6  0.125000
03c7c0ace395d80182db07ae2c30f034      1       0  0.000000
04a75b75d5f4f3a16b0178fbe382da00      1       1  1.000000
...                                 ...     ...       ...
fd7c4cdfbfb7964b441618d54f88c38b      1       0  0.000000
fd7d977e75d1ac5cfe6b93ffabb150b1      1       0  0.000000
fe82aeadeaea2186478fe6353d6d5301      8       2  0.250000
ff3416719616ad4921acb8c74e21d6f0     11       0  0.000000
ffc62d6945fd1423539ec6d96326c37c      1       1  1.000000

[495 rows x 3 columns]

- Para cada SR, qual a receita média declarada dos leads?

In [ ]:
tabela_mqls.groupby('sr_id')['declared_monthly_revenue'].mean().sort_values(ascending=False).to_frame("receita_media")

                                  receita_media
sr_id
4ef15afb4b2723d8f3d81e51ec7afefe  377293.233083
de63de0d10a6012430098db33c679b0b  151415.094340
9749123c950bf8363ace42cb1c2d0815  103571.428571
9d12ef1a7eca3ec58c545c678af7869c   43333.333333
4b339f9567d060bcea4f5136b9f5949e   27777.777778
a8387c01a09e99ce014107505b92388c   24038.692308
34d40cdaf94010a1d05b0d6212f9e909   19000.000000
56bf83c4bb35763a51c2baab501b4c67   12500.000000
6aa3b86a83d784b05f0e37e26b20860d    8000.000000
068066e24f0c643eb1d089c7dd20cd73    7037.037037
495d4e95a8cf8bbf8b432b612a2aa328    6666.666667
0a0fb2b07d841f84fb6714e35c723075    6000.000000
d3d1e91a157ea7f90548eef82f1955e3    4939.024390
2695de1affa7750089c0455f8ce27021    1694.915254
85fc447d336637ba1df43e793199fbc8    1562.500000
b90f87164b5f8c2cfa5c8572834dbe3f       0.000000
c638112b43f1d1b86dcabb0da720c901       0.000000
060c0a26f19f4d66b42e0d8796688490       0.000000
9e4d1098a3b0f5da39b0bc48f9876645       0.000000
9ae085775a198122c5586fa830ff7f2b       0.000000
6565aa9ce3178a5caf6171827af3a9ba       0.000000
fbf4aef3f6915dc0c3c97d6812522f6a       0.000000

- Para cada SR, quantos de cada business_type a pessoa converteu?

In [ ]:
tabela_mqls.pivot_table(columns='business_type', index='sr_id', values='is_closed',aggfunc='sum').fillna(0)

business_type                     manufacturer  other  reseller
sr_id
060c0a26f19f4d66b42e0d8796688490           9.0    0.0      23.0
068066e24f0c643eb1d089c7dd20cd73           6.0    0.0      21.0
0a0fb2b07d841f84fb6714e35c723075           0.0    1.0       0.0
2695de1affa7750089c0455f8ce27021          16.0    0.0      42.0
34d40cdaf94010a1d05b0d6212f9e909           1.0    1.0       8.0
495d4e95a8cf8bbf8b432b612a2aa328          14.0    0.0      47.0
4b339f9567d060bcea4f5136b9f5949e           2.0    0.0       6.0
4ef15afb4b2723d8f3d81e51ec7afefe          43.0    0.0      90.0
56bf83c4bb35763a51c2baab501b4c67           8.0    0.0      16.0
6565aa9ce3178a5caf6171827af3a9ba          19.0    0.0      54.0
6aa3b86a83d784b05f0e37e26b20860d           0.0    0.0       1.0
85fc447d336637ba1df43e793199fbc8          25.0    0.0      39.0
9749123c950bf8363ace42cb1c2d0815           2.0    0.0       5.0
9ae085775a198122c5586fa830ff7f2b          15.0    0.0      36.0
9d12ef1a7eca3ec58c545c678af7869c           2.0    0.0       4.0
9e4d1098a3b0f5da39b0bc48f9876645          10.0    0.0      14.0
a8387c01a09e99ce014107505b92388c           4.0    1.0      21.0
b90f87164b5f8c2cfa5c8572834dbe3f           0.0    0.0       1.0
c638112b43f1d1b86dcabb0da720c901          12.0    0.0      22.0
d3d1e91a157ea7f90548eef82f1955e3          19.0    0.0      61.0
de63de0d10a6012430098db33c679b0b          12.0    0.0      40.0
fbf4aef3f6915dc0c3c97d6812522f6a          23.0    0.0      36.0

- Para cada SR, quantos de cada lead_behaviour_profile a pessoa converteu?

In [ ]:
tabela_mqls.pivot_table(columns='lead_behaviour_profile', index='sr_id', values='is_closed',aggfunc='sum').fillna(0)

lead_behaviour_profile,cat,"cat, wolf",eagle,"eagle, cat","eagle, wolf",shark,"shark, cat","shark, wolf",wolf
sr_id,,,,,,,,,
060c0a26f19f4d66b42e0d8796688490,15.0,0.0,2.0,0.0,0.0,1.0,0.0,0.0,6.0
068066e24f0c643eb1d089c7dd20cd73,11.0,1.0,7.0,0.0,0.0,1.0,0.0,1.0,4.0
0a0fb2b07d841f84fb6714e35c723075,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2695de1affa7750089c0455f8ce27021,34.0,1.0,9.0,0.0,0.0,2.0,1.0,0.0,6.0
34d40cdaf94010a1d05b0d6212f9e909,3.0,2.0,4.0,0.0,1.0,0.0,0.0,0.0,0.0
495d4e95a8cf8bbf8b432b612a2aa328,30.0,0.0,6.0,1.0,0.0,2.0,0.0,0.0,7.0
4b339f9567d060bcea4f5136b9f5949e,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
4ef15afb4b2723d8f3d81e51ec7afefe,58.0,2.0,23.0,0.0,0.0,0.0,0.0,0.0,12.0
56bf83c4bb35763a51c2baab501b4c67,17.0,0.0,2.0,0.0,0.0,2.0,0.0,0.0,2.0
6565aa9ce3178a5caf6171827af3a9ba,31.0,0.0,13.0,0.0,0.0,0.0,0.0,0.0,11.0
6aa3b86a83d784b05f0e37e26b20860d,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
85fc447d336637ba1df43e793199fbc8,41.0,0.0,7.0,0.0,0.0,4.0,0.0,0.0,11.0
9749123c950bf8363ace42cb1c2d0815,2.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,4.0
9ae085775a198122c5586fa830ff7f2b,12.0,0.0,4.0,0.0,1.0,1.0,0.0,0.0,5.0
9d12ef1a7eca3ec58c545c678af7869c,3.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
9e4d1098a3b0f5da39b0bc48f9876645,16.0,0.0,6.0,0.0,0.0,2.0,0.0,0.0,0.0
a8387c01a09e99ce014107505b92388c,14.0,0.0,6.0,1.0,0.0,0.0,0.0,0.0,3.0
b90f87164b5f8c2cfa5c8572834dbe3f,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
c638112b43f1d1b86dcabb0da720c901,17.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,3.0
d3d1e91a157ea7f90548eef82f1955e3,28.0,0.0,12.0,0.0,1.0,2.0,0.0,0.0,11.0
de63de0d10a6012430098db33c679b0b,37.0,0.0,7.0,0.0,0.0,4.0,0.0,0.0,5.0
fbf4aef3f6915dc0c3c97d6812522f6a,30.0,0.0,9.0,0.0,0.0,2.0,0.0,0.0,2.0

- Para cada SR, quantos de cada lead_type a pessoa converteu?

In [ ]:
tabela_mqls.pivot_table(columns='lead_type', index='sr_id', values='is_closed',aggfunc='sum').fillna(0)

lead_type,industry,offline,online_beginner,online_big,online_medium,online_small,online_top,other
sr_id,,,,,,,,
060c0a26f19f4d66b42e0d8796688490,8.0,1.0,3.0,2.0,15.0,3.0,0.0,0.0
068066e24f0c643eb1d089c7dd20cd73,2.0,7.0,0.0,3.0,12.0,3.0,0.0,0.0
0a0fb2b07d841f84fb6714e35c723075,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2695de1affa7750089c0455f8ce27021,4.0,12.0,6.0,9.0,19.0,8.0,1.0,0.0
34d40cdaf94010a1d05b0d6212f9e909,1.0,2.0,1.0,1.0,4.0,0.0,0.0,1.0
495d4e95a8cf8bbf8b432b612a2aa328,11.0,5.0,1.0,14.0,25.0,5.0,1.0,0.0
4b339f9567d060bcea4f5136b9f5949e,2.0,0.0,0.0,2.0,5.0,0.0,0.0,0.0
4ef15afb4b2723d8f3d81e51ec7afefe,18.0,22.0,5.0,21.0,49.0,13.0,3.0,0.0
56bf83c4bb35763a51c2baab501b4c67,1.0,6.0,4.0,2.0,9.0,2.0,0.0,0.0
6565aa9ce3178a5caf6171827af3a9ba,9.0,9.0,4.0,10.0,38.0,4.0,0.0,0.0
6aa3b86a83d784b05f0e37e26b20860d,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
85fc447d336637ba1df43e793199fbc8,13.0,6.0,5.0,13.0,20.0,5.0,2.0,0.0
9749123c950bf8363ace42cb1c2d0815,2.0,1.0,0.0,1.0,2.0,1.0,0.0,0.0
9ae085775a198122c5586fa830ff7f2b,13.0,4.0,6.0,6.0,18.0,2.0,0.0,0.0
9d12ef1a7eca3ec58c545c678af7869c,0.0,2.0,0.0,0.0,3.0,1.0,0.0,0.0
9e4d1098a3b0f5da39b0bc48f9876645,5.0,0.0,1.0,4.0,11.0,2.0,1.0,0.0
a8387c01a09e99ce014107505b92388c,2.0,4.0,4.0,3.0,9.0,3.0,0.0,1.0
b90f87164b5f8c2cfa5c8572834dbe3f,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
c638112b43f1d1b86dcabb0da720c901,5.0,7.0,2.0,3.0,14.0,3.0,1.0,0.0
d3d1e91a157ea7f90548eef82f1955e3,12.0,4.0,11.0,17.0,25.0,11.0,2.0,0.0
de63de0d10a6012430098db33c679b0b,7.0,8.0,3.0,7.0,22.0,5.0,1.0,0.0
fbf4aef3f6915dc0c3c97d6812522f6a,8.0,4.0,1.0,8.0,30.0,6.0,2.0,0.0